ARG MATCHER_REPO
ARG MATCHER_GIT_REF
FROM denoland/deno:alpine-1.36.1

RUN apk --no-cache add git
WORKDIR /app

# Clone the matcher
ENV MATCHER_REPO=${MATCHER_REPO:-https://github.com/ix0rai/matcher.git}
ENV MATCHER_GIT_REF=${MATCHER_GIT_REF:-5f59262c422b3526ad4683c70b5a6f3e931e0ca3}
RUN git clone ${MATCHER_REPO} . && git reset --hard ${MATCHER_GIT_REF} && git clean -df && \
    git config user.email "me@example.com" && git config user.name "Me"

VOLUME /app/qm
